apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartdispute-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smartdispute
  template:
    metadata:
      labels:
        app: smartdispute
    spec:
      containers:
      - name: app
        image: smartdispute-app:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3